name: Validate JSON

on:
  pull_request:
    branches: [master]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schemas/profiles.json
          INPUT_JSONS: /static/profiles.json
